/**
 * Sequelize Models Entry Point
 * 
 * This file creates the Sequelize instance and initializes models.
 * Model definitions are auto-generated by sequelize-auto in init-models.js.
 * Run `node scripts/generate-models.js` to regenerate model files.
 * 
 * Association aliases are defined here for friendly naming in queries.
 */

'use strict';

import { Sequelize } from 'sequelize';
import initModels from './init-models.js';

// 创建 Sequelize 实例
const sequelize = new Sequelize(
  process.env.DB_NAME,
  process.env.DB_USER,
  process.env.DB_PASSWORD,
  {
    host: process.env.DB_HOST || 'localhost',
    port: process.env.DB_PORT || 3306,
    dialect: 'mysql',
    logging: process.env.NODE_ENV === 'development' 
      ? (msg) => console.log('[SQL]', msg) 
      : false,
    pool: {
      max: 10,
      min: 0,
      acquire: 30000,
      idle: 10000,
    },
    define: {
      timestamps: true,
      underscored: true,
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      freezeTableName: true,
    },
    dialectOptions: {
      decimalNumbers: true,
    },
  }
);

// 初始化模型
const models = initModels(sequelize);

// ============ 关联别名由 init-models.js 自动生成 ============
// 所有 belongsToMany 关联的别名由 sequelize-auto 自动生成
// 运行 `node scripts/generate-models.js` 会重新生成 init-models.js

/**
 * 初始化数据库连接
 */
async function initDatabase() {
  try {
    await sequelize.authenticate();
    console.log('✅ Database connection established');
    return models;
  } catch (error) {
    console.error('❌ Database connection failed:', error);
    throw error;
  }
}

export {
  models,
  sequelize,
  Sequelize,
  initDatabase,
};

export default {
  ...models,
  sequelize,
  Sequelize,
  initDatabase,
};
