/**
 * Sequelize Models Entry Point
 * 
 * This file creates the Sequelize instance and initializes models.
 * Model definitions are auto-generated by sequelize-auto in init-models.js.
 * Run `node scripts/generate-models.js` to regenerate model files.
 * 
 * Association aliases are defined here for friendly naming in queries.
 */

'use strict';

import { Sequelize } from 'sequelize';
import initModels from './init-models.js';

// 创建 Sequelize 实例
const sequelize = new Sequelize(
  process.env.DB_NAME,
  process.env.DB_USER,
  process.env.DB_PASSWORD,
  {
    host: process.env.DB_HOST || 'localhost',
    port: process.env.DB_PORT || 3306,
    dialect: 'mysql',
    logging: process.env.NODE_ENV === 'development' 
      ? (msg) => console.log('[SQL]', msg) 
      : false,
    pool: {
      max: 10,
      min: 0,
      acquire: 30000,
      idle: 10000,
    },
    define: {
      timestamps: true,
      underscored: true,
      createdAt: 'created_at',
      updatedAt: 'updated_at',
      freezeTableName: true,
    },
  }
);

// 初始化模型
const models = initModels(sequelize);

// ============ 覆盖关联别名 ============
// init-models.js 生成的别名不够友好（如 'tag_id_kb_tags'）
// 这里重新定义 belongsToMany 关联，使用更友好的别名

// KbArticle <-> KbTag (通过 kb_article_tags)
models.kb_article.belongsToMany(models.kb_tag, {
  through: models.kb_article_tag,
  foreignKey: 'article_id',
  otherKey: 'tag_id',
  as: 'tags',  // 友好别名
});
models.kb_tag.belongsToMany(models.kb_article, {
  through: models.kb_article_tag,
  foreignKey: 'tag_id',
  otherKey: 'article_id',
  as: 'articles',  // 友好别名
});

// Expert <-> Skill (通过 expert_skills)
models.expert.belongsToMany(models.skill, {
  through: models.expert_skill,
  foreignKey: 'expert_id',
  otherKey: 'skill_id',
  as: 'skills',  // 友好别名
});
models.skill.belongsToMany(models.expert, {
  through: models.expert_skill,
  foreignKey: 'skill_id',
  otherKey: 'expert_id',
  as: 'experts',  // 友好别名
});

// User <-> Role (通过 user_roles)
models.user.belongsToMany(models.role, {
  through: models.user_role,
  foreignKey: 'user_id',
  otherKey: 'role_id',
  as: 'roles',  // 友好别名
});
models.role.belongsToMany(models.user, {
  through: models.user_role,
  foreignKey: 'role_id',
  otherKey: 'user_id',
  as: 'users',  // 友好别名
});

// Role <-> Permission (通过 role_permissions)
models.role.belongsToMany(models.permission, {
  through: models.role_permission,
  foreignKey: 'role_id',
  otherKey: 'permission_id',
  as: 'permissions',  // 友好别名
});
models.permission.belongsToMany(models.role, {
  through: models.role_permission,
  foreignKey: 'permission_id',
  otherKey: 'role_id',
  as: 'roles',  // 友好别名
});

/**
 * 初始化数据库连接
 */
async function initDatabase() {
  try {
    await sequelize.authenticate();
    console.log('✅ Database connection established');
    return models;
  } catch (error) {
    console.error('❌ Database connection failed:', error);
    throw error;
  }
}

export {
  models,
  sequelize,
  Sequelize,
  initDatabase,
};

export default {
  ...models,
  sequelize,
  Sequelize,
  initDatabase,
};
